language: node_js
node_js:
  - "10"
cache: npm

before_script:
        - npm install -g license-cli
        - cd .
        - license-cli auth $FOSSA_API_TOKEN
        - license-cli scan -r $TRAVIS_COMMIT
